### ISSUE TITLE
Missing steps for beginners @ creating a basic dapp

### ISSUE THREAD

**Issue by dee22** [LiskArchive/lisk-dapps-docs#6]
This issue refers to the Tutorial seen here:
https://lisk.io/documentation?i=lisk-dapps-docs/BasicDapp

The following steps are not documented and could cause problems.
For someone who creates a new account on github.com or just used https until now, the following steps are maybe also required:
1. Install git
2. generate ssh key-pair
3. add private-key to ssh-agent
4. add public-key to github.com account

**Comment by Isabello** [comment]
I think better would be to change the sdk/cli to allow https instead of forcing git over ssh in all cases.
